app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
redirect:
    resource: "@AppBundle/Controller/RedirectingController.php"
    type:     annotation
    